### ISSUE TITLE
Gutenberg: Add expanded versions of core side panels

### ISSUE THREAD

**Issue by helen** [10up/SketchPress#22]
There are symbols for things like the "publish metabox" but I'm not seeing the expanded contents of the various panels (or whatever they're called) in there. Apologies if I've missed it! Screenshot of what I mean:

<img width="282" alt="screen shot 2018-05-02 at 4 17 20 pm" src="https://user-images.githubusercontent.com/906334/39547061-7173f1f4-4e24-11e8-9d05-d84cd4591e7d.png">

**Comment by jarahsames** [comment]
@helen thanks for calling this to my attention. expanded states are essentially made up of various Sketch symbols and are not currently their own stand-alone symbols (because of the many variances they could have). So essentially the would be built per usage basis (e.g. tags would be meta box open, change the title, and text input field).

That being said, I will add this as a feature request and let you know when it is updated.

**Comment by helen** [comment]
@jarahsames Yup, totally understand and it wasn't horrible to create one by any means. It may be that "just" having a few groupings of symbols (whatever it's called, don't have the Sketch vocabulary!) that represent the built-in core boxes would be enough - a category checkbox tree, tag input with inputted tags (I don't see any representation of that control right now), and featured image with image selected.

**Comment by jarahsames** [comment]
@helen SketchPress is updated to include new meta boxes as well as typical states for them (e.g. published vs. unpublished posts). Screen capture attached. Closing issue -- please feel free to reopen or create a new one if you feel like anything specific is missing. Thanks!

![typical metaboxes](https://user-images.githubusercontent.com/22618076/45852017-838d8e80-bcf2-11e8-9118-ca585ab99976.png)
